### ISSUE TITLE
[Bug]安装失败

### ISSUE THREAD

**Issue by LS-King** [Richasy/Bili.Uwp#231]
## Bug 描述

系统开启开发者模式，管理员身份运行 Powershell 7.1.4 ，执行 Install.ps1 安装过程中报错

## 复现步骤

重现问题的步骤：

1. 管理员身份运行 Powershell 7.1.4 ，执行 Install.ps1
2. 执行至 Add-AppDevPackage.ps1 出现如下报错
```
Add-AppxPackage: C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackage.ps1:487
Line |
 487 |              Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep …
     |              ~~~~~~~~~~~~~~~
     | The 'Add-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For more
     | information, run 'Import-Module Appx'.

错误: 未能安装应用程序。
```

## 预期的行为

正常完成安装

## Get-Error 信息

```
Exception             :
    Type           : System.Management.Automation.CommandNotFoundException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The 'Add-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For m
ore information, run 'Import-Module Appx'.
            HResult : -2146233087
        TargetObject          : Add-AppxPackage
        CategoryInfo          : ObjectNotFound: (Add-AppxPackage:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
        InvocationInfo        :
            ScriptLineNumber : 487
            OffsetInLine     : 13
            HistoryId        : 2
            ScriptName       : C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackage.ps1
            Line             : Add-AppxPackage -Path $DeveloperPackagePath.FullName -DependencyPath $DependencyPackages.FullN
ame -ForceApplicationShutdown

            PositionMessage  : At C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackage.ps1:487 char:13
                               +             Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep …
                               +             ~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64
            PSCommandPath    : C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackage.ps1
            InvocationName   : Add-AppxPackage
            CommandOrigin    : Internal
        ScriptStackTrace      : at InstallPackageWithDependencies, C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppD
evPackage.ps1: line 487
                                at DoStandardOperations, C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackage.ps1: line
 670
                                at <ScriptBlock>, C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackage.ps1: line 682
                                at <ScriptBlock>, <No file>: line 1
                                at <ScriptBlock>, C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Install.ps1: line 47
                                at <ScriptBlock>, <No file>: line 1
    CommandName    : Add-AppxPackage
    TargetSite     :
        Name          : CheckActionPreference
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation, Version=7.1.4.0, Cul
ture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace     :
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    Message        : The 'Add-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For mo
re information, run 'Import-Module Appx'.
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        Type           : System.Management.Automation.CmdletInvocationException
        ErrorRecord    :
            Exception             :
                Type       : System.PlatformNotSupportedException
                TargetSite :
                    Name          : GetExportedTypes
                    DeclaringType : System.Reflection.RuntimeAssembly, System.Private.CoreLib, Version=5.0.0.0, Culture=neutr
al, PublicKeyToken=7cec85d7bea7798e
                    MemberType    : Method
                    Module        : System.Private.CoreLib.dll
                StackTrace :
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSna
pInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSn
apInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleN
ame, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlag
s manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disa
bleFormatUpdates)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecification moduleSp
ecification, String moduleBase, Boolean searchModulePath, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcess
ingFlags manifestProcessingFlags, Boolean loadTypesFiles, Boolean loadFormatFiles, Object privateData, Boolean& found, String shortMod
uleName, Nullable`1 manifestLanguageMode)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptIn
fo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumV
ersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String
prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& f
ound, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String na
me)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions importModuleOpti
ons, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
                Message    : Operation is not supported on this platform. (0x80131539)
                Source     : System.Private.CoreLib
                HResult    : -2146233031
            CategoryInfo          : NotSpecified: (:) [Import-Module], PlatformNotSupportedException
            FullyQualifiedErrorId : System.PlatformNotSupportedException,Microsoft.PowerShell.Commands.ImportModuleCommand
            InvocationInfo        :
                MyCommand       : Import-Module
                HistoryId       : 2
                InvocationName  : Import-Module
                CommandOrigin   : Internal
            ScriptStackTrace      : at InstallPackageWithDependencies, C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-
AppDevPackage.ps1: line 487
                                    at DoStandardOperations, C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackage.ps1:
line 670
                                    at <ScriptBlock>, C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackage.ps1: line 68
2
                                    at <ScriptBlock>, <No file>: line 1
                                    at <ScriptBlock>, C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Install.ps1: line 47
                                    at <ScriptBlock>, <No file>: line 1
            PipelineIterationInfo :



        TargetSite     :
            Name          : Invoke
            DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.1.4.
0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        StackTrace     :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PS
InvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvoca
tionSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings s
ettings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T]()
   at System.Management.Automation.CommandDiscovery.AutoloadSpecifiedModule(String moduleName, ExecutionContext context, SessionStateE
ntryVisibility visibility, Exception& exception)
        Message        : Operation is not supported on this platform. (0x80131539)
        InnerException :
            Type       : System.PlatformNotSupportedException
            TargetSite :
                Name          : GetExportedTypes
                DeclaringType : System.Reflection.RuntimeAssembly, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e
                MemberType    : Method
                Module        : System.Private.CoreLib.dll
            StackTrace :
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSna
pInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSn
apInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleN
ame, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlag
s manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disa
bleFormatUpdates)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecification moduleSp
ecification, String moduleBase, Boolean searchModulePath, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcess
ingFlags manifestProcessingFlags, Boolean loadTypesFiles, Boolean loadFormatFiles, Object privateData, Boolean& found, String shortMod
uleName, Nullable`1 manifestLanguageMode)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptIn
fo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumV
ersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String
prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& f
ound, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String na
me)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions importModuleOpti
ons, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
            Message    : Operation is not supported on this platform. (0x80131539)
            Source     : System.Private.CoreLib
            HResult    : -2146233031
        Source         : System.Management.Automation
        HResult        : -2146233087
    Source         : System.Management.Automation
    HResult        : -2146233087
TargetObject          : Add-AppxPackage
CategoryInfo          : ObjectNotFound: (Add-AppxPackage:String) [], CommandNotFoundException
FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
InvocationInfo        :
    ScriptLineNumber : 487
    OffsetInLine     : 13
    HistoryId        : 2
    ScriptName       : C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackage.ps1
    Line             : Add-AppxPackage -Path $DeveloperPackagePath.FullName -DependencyPath $DependencyPackages.FullName -For
ceApplicationShutdown

    PositionMessage  : At C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackage.ps1:487 char:13
                       +             Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep …
                       +             ~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64
    PSCommandPath    : C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackage.ps1
    InvocationName   : Add-AppxPackage
    CommandOrigin    : Internal
ScriptStackTrace      : at InstallPackageWithDependencies, C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackag
e.ps1: line 487
                        at DoStandardOperations, C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackage.ps1: line 670
                        at <ScriptBlock>, C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Add-AppDevPackage.ps1: line 682
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, C:\Users\jxy_1\Desktop\Bili.Uwp_2.2109.2001.0_x64\Install.ps1: line 47
                        at <ScriptBlock>, <No file>: line 1
```

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github

应用版本：{技术预览版 - 3}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by Richasy** [comment]
请不要使用PowerShell Core安装，而是使用自带的Windows PowerShell, 这一点在README或者安装说明里有写
